<a href = "https://iopscience.iop.org/article/10.1088/17489326/abfba1">
    <img src = "imgs/imgFive.jpg" alt = " Bar graphs that represent the percent reduction/increase of each environmental footprint compared to the national average data center environmental footprint." />
</a>

<p class = "image_desc">
    Image and information obtained from "Siddik, M. A. B., Shehabi, A., & Marston, L. (2021). The environmental footprint of data centers in the United States. Environmental Research Letters, 16(6), Article 064017. https://doi.org/10.1088/17489326/abfba1"
</p>

<p>
   The scale of what is being discussed, is what caught my attention to this paper. After hearing the facts on how much electricity data centers use, as well as the water it uses. I was wondering exactly how much power these data centers used. This paper was exactly what I wanted to find, what I found out is that data centers, in 2018, took exactly 76 terawatt hours of energy per year, to give you some scale, a single terawatt is enough electricity to power a single home, for a 100 million hours. Or the entire state of California for a week and a half. That is being drawn constantly from the US power grid. This paper talks about as well the water it takes, It not only takes most of the subbasins of water in the United States, but All of them, or 2,110 subbasins total. The water consumption was split in two categories, direct and indirect.
</p>


<p id="topicFiveMore" style="display: none;">

    Direct water consumption, or the water that is used on location to cool a data center, in reality only takes up one fourth of the total percentages of water usage from these data centers. The other three fourths are categorized as indirect, or water consumed by the power plants generating the electricity that runs the data center. As well as the water used by the water treatment plants, showing that it not only is the data center that is negative. But the entire supply chain as argued by the other topics. Most of the water usage not even being taken into account, as the only water that is tracked in a measurable quantity is the direct water usage that these tech companies abuse. In 2018, the estimated annual water footprint for these date centers reached 513 million cubic meters. Consuming more then the national total of water consumption by citizen, which was 444.3 million cubic meters of water. Almost a 70 million cubic meter water difference. With 90% of the water used by these tech companies coming from US watersheds. Marston, a researcher even acknowledges this by saying that these data centers are in the top 10 water consumers in the nation. With co-author and researcher Shehabi stating that, "this is pretty unusual for an industry". That was 8 years ago now, before the exponential growth and investments made towards data centers.

    What directly affects Indigenous communities more, that was supported by this paper, is the raw water volume alone, as well as the water scarcity footprint concept. Essentially it measures how scarce water is already in that area. With the higher the number meaning that water, from that specific basin, is harder to extract and harder to come by. The tests that the researchers conducted, as well as averaging the nations totals out. Came to be Indigenous Communities face more then 17.9 cubic meters of water scarcity equivalent compared to each megawatt hour of electricity used. That doesn't sound too bad, however compared to the nation average of 7.1 cubic meters per megawatt hour per community. Flat out proving, that tech companies are going out of there way to already find stressed sub basins, and then attempting to extract as much profit as possible. The paper describes areas that are most in danger, being those Community's that are in the Western and Southwestern United States. As these sub basins are especially vulnerable due to already made colonial laws that dismantled protections for these Indigenous lands where the sub basins sit. So on the local scale, it shows that these data centers require more then 15% - 20% of the available water already in the sub basins. Causing residents of the community to face unreliable water usage. With the companies, not paying any tax on said water.

    As of 2023, the latest update we have on the total used electricity that these data centers consumed raised to over 176 terawatt hours. More then doubling the expected growth. With this continuous exponential growth, it is estimated we will be at 325 - 580 terawatt hours. A incomprehensible amount of energy.
    
</p>
