<a href = "https://www.nationofchange.org/2026/04/23/data-colonialism-native-communities-fight-ai-data-centers-on-indigenous-land/">
    <img src = "imgs/imgThree.png" alt = "Amy Goodman arrested Screen cap, 2008" />
</a>
<p class = "image_desc">
    Screen Cap of footage of Amy Goodman arrested Circa. 2008, Article information from "Goodman, A. Democracy Now! & Nation of Change. (2026, April 23). Data colonialism: Native communities fight AI data centers on Indigenous land. Nation of Change. https://www.nationofchange.org/2026/04/23/data-colonialism-native-communities-fight-ai-data-centers-on-indigenous-land/
</p>

<p>
    Democracy Now! Earth Day 2026 Broadcast transcript/text features Krystal Two Bulls, as mentioned before she is an activist, and executive director of Honor the Earth. She begins with a subtle re framing of the conversation. Instead of data centers being treated as the single issue, she wants to discuss the entire supply chain of the data center. From the Lithium mines that take the precious metals, to the water basins that is being pumped out. That takes into account as well the conditions inside of the Data Center like the air conditioners. A detail she also mentions is the fact that Uranium, the nuclear power Uranium, is now added to the list of critical materials, making it eligible for mining in Indigenous Lands. That layering, from the lithium, gas, uranium, that targets these Indigenous Community in specific. 
</p>


<p id="topicThreeMore" style="display: none;">
    Going into detail on why it is not random. Mentioning six specific reasons that this keeps happening. Access to large land bases, for a relatively lower price. Access to water. Built in Tax exceptions. Lack of a legal infrastructure in most of these communities, and the appeal to communities in poverty, with the bait and switch tactic is specifically it keeps happening. Because of communities that are limited economically due to colonial eurocentric ideals still being prevalent within most governments. Such as the United States of America. The worst of the lies being the point of creating jobs, showing that they understand the need for more economic stimulus into the communities, yet using it as leverage essentially to gain monetary control over the boards that see this. Of course most Indigenous Communities know this already, so they use shell companies, subsidiaries, and even in some cases, Native owned energy companies as essentially a front. In order to get these communities to hear them out, after which by the time the Communities find out the true identity, much later on. 

    The NDA issue, as brought up earlier, is described using an example. She uses how these companies act as if they are interested in adding solar panels, and other renewable energy sources to help out the community. Then after that, they are presented an NDA, but not any firm contract on adding any renewable energy, essentially just using it to get Communities to sign an NDA, which they then use as a legal strong arm into getting data centers into the area. With Members from the community not getting a say in it. That problem she mentions as well is being battled with an open source / crowd sourced map where proposals are being made. Which in the time of writing this sits at around 160 - 190 hyper scale data centers, specifically on Indigenous Land. The harm that comes from these hyper scale data centers are too long to name, so a couple of the most important ones that are mentioned by her are how Existing hyper scale data centers take up from 300,000 to 5 million gallons of clean drinking water per year, not water that is repurposed, but fresh drinking water. Another being the noise pollution generated from a average hyper scale data center is 97 decibels, that being too if you are exposed for too long to that, you will suffer life long hearing damage. Not to mention the fact that it increases temperature around the general area by up to 16 degrees. She specifically mentioned a woman in Montana, she lives in a mobile home, and this non-drastic winter, she got billed 900 dollars for the electricity. A direct result of the data center that popped up near her.
</p>
